### ISSUE TITLE
Thanks for creating :) ... a couple of queries 

### ISSUE THREAD

**Issue by mannp** [r0b2g1t/k0s-oracle-cloud-infrastructure-cluster#1]
Hi @r0b2g1t 

I am intrigued about the spec of the nodes?

```
  controller_instance_config = {
    shape_id = "VM.Standard.A1.Flex"
    ocpus    = 2
    ram      = 12

  worker_instance_config = {
    shape_id = "VM.Standard.E2.1.Micro"
    ocpus    = 1
    ram      = 1
```

Why so much ram for the controllers? With so little for the workers?

Also

`terraform output -raw k0s_cluster | k0sctl kubeconfig --disable-telemetry --config - > ~/.kube/config`

The kubeconfig refers to the private ip of the k0s-controller-1, which seems to expect ssh'ing in to the node first. Using the public ip for this node allows kubectl to work, though.

Cheers

**Comment by r0b2g1t** [comment]
Hi, thanks for your question. 🙂 There are two reasons for selecting the shapes in this order.
First, many container images are not available for arm systems. For this reason I had selected the Micro shape for the work with the x64 system.
Second, the workload of the controller was too high for the 1 OCPUs and 1GB of RAM.

Maybe you can try to exchange the shapes in the ```variables.tf``` and give feedback if it works well.

And about the kubectl config settings of the public IP, yes this is possible but keep in mind it could be a security issue to allow ingress traffic to your Kubernetes API from public. For this reason I use mostly a VPN and access the API from the private network.

**Comment by mannp** [comment]
Hi there, that's fair enough, of course :) 

I had presumed the use of the small amd64 workers was the restrictions on arm images, and I believe the reverse is not allowed within the free tier (but I may be wrong there)

I don't want the api open to the public at all, as I forward ssh, to access the k3s apis elsewhere.

My point was that the kubeconfig created doesn't work as documented.

**Comment by r0b2g1t** [comment]
Yes, you can only use the smallest amd64 VMs. The arm systems could be larger.

And yes you can use the API forward via ssh to access the cluster. The configuration via the command in the documentation use the private IP of the controller. Sorry for the misunderstanding.

**Comment by mannp** [comment]
Would you envisage any issues me changing to 4 arm nodes each with 6g mem and ocpus = 1?
